# Generated by Django 5.2.7 on 2026-01-02 08:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.IntegerField(choices=[('0', 'created'), ('1', "deleted',")], db_column='action')),
                ('points', models.IntegerField(db_column='Points', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(db_column='Country_name', max_length=30)),
                ('country_code', models.CharField(db_column='Country_code', max_length=20)),
                ('country_tel_code', models.CharField(db_column='Country_tel_code', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
        ),
        migrations.CreateModel(
            name='SecurityInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('two_factor_auth', models.BooleanField(blank=True, db_column='Two Factor Auth', default=False, null=True)),
                ('last_password_change_at', models.DateTimeField(blank=True, db_column='Last Password Change At', null=True)),
                ('reset_phone_no', models.CharField(blank=True, db_column='reset_mobile_no', max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(db_column='Language', default='en', max_length=50)),
                ('theme', models.IntegerField(blank=True, db_column='Theme', null=True)),
                ('time_zone', models.CharField(db_column='Time_Zone', default=True, max_length=100, null=True)),
                ('notification_Preference', models.CharField(db_column='Notification_Preference', default=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_column='uuid', default=uuid.uuid4, editable=False, unique=True)),
                ('dob', models.DateField(blank=True, db_column='dob', max_length=50, null=True)),
                ('gender', models.CharField(blank=True, db_column='gender', max_length=50, null=True)),
                ('picture_path', models.CharField(blank=True, db_column='picture_path', max_length=200, null=True)),
                ('phone_no', models.CharField(blank=True, db_column='mobile_no', max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('user', models.OneToOneField(db_column='user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=10)),
                ('generated_date', models.DateField(auto_now_add=True)),
                ('total_bookings', models.IntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cancelled_bookings', models.IntegerField(default=0)),
                ('active_buses', models.IntegerField(default=0)),
                ('most_popular_route', models.CharField(blank=True, max_length=255, null=True)),
                ('least_popular_route', models.CharField(blank=True, max_length=255, null=True)),
                ('peak_booking_time', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, to='auth_sys.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='TotalReportSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_bookings', models.IntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_cancelled', models.IntegerField(default=0)),
                ('total_buses', models.IntegerField(default=0)),
                ('total_routes', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, to='auth_sys.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(blank=True, db_column='bio', max_length=2000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('user', models.OneToOneField(db_column='user', on_delete=django.db.models.deletion.CASCADE, to='auth_sys.customuser')),
            ],
        ),
    ]
