# Generated by Django 5.2.7 on 2025-10-22 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_sys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='theme',
            field=models.IntegerField(blank=True, db_column='Theme', null=True),
        ),
    ]
