# Generated by Django 5.2.7 on 2026-01-13 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_sys', '0002_remove_country_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='updated_at'),
        ),
    ]
