# Generated by Django 5.2.7 on 2026-01-13 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_sys', '0003_country_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='latest_report',
            field=models.ForeignKey(blank=True, db_column='latest_report', null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth_sys.report'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_summary',
            field=models.ForeignKey(blank=True, db_column='total_summary', null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth_sys.totalreportsummary'),
        ),
    ]
