# Generated by Django 5.2.7 on 2026-01-13 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_sys', '0005_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('SUPERADMIN', 'Superadmin'), ('ADMIN2', 'AdminLevel2'), ('STAFF', 'Staff'), ('STUDENT', 'Student')], default='SUPERADMIN', max_length=20),
        ),
    ]
