# Generated by Django 5.2.7 on 2026-01-20 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_sys', '0006_alter_customuser_role'),
        ('dispatch_sys', '0006_rename_center_name_center_c_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='center_id',
            field=models.ForeignKey(blank=True, db_column='center', null=True, on_delete=django.db.models.deletion.CASCADE, to='dispatch_sys.center'),
        ),
    ]
