# Generated by Django 5.2.7 on 2026-01-11 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('printed_quantity', models.IntegerField(default=0)),
                ('left_quantity', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'book',
            },
        ),
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center_name', models.CharField(max_length=100)),
                ('tel_no', models.CharField(max_length=12)),
            ],
            options={
                'db_table': 'center',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('course_code', models.CharField(max_length=30, unique=True)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('years', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'course',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'db_table': 'departments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(db_column='d_name', max_length=100)),
                ('info', models.CharField(db_column='info', max_length=1000)),
            ],
            options={
                'db_table': 'district',
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('dean_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('established_date', models.DateField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='faculty_logos/')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Faculties',
                'db_table': 'faculty',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CenterBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('approved', models.BooleanField(default=False)),
                ('allocation_quantity', models.IntegerField(default=0)),
                ('books', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='centerbook', to='dispatch_sys.book')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='dispatch_sys.center')),
            ],
            options={
                'db_table': 'center_book',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_books', to='dispatch_sys.course'),
        ),
        migrations.CreateModel(
            name='DegreeProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_program', models.CharField(max_length=100)),
                ('info', models.CharField(max_length=1000)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='degree_department', to='dispatch_sys.department')),
            ],
            options={
                'db_table': 'degree_program',
            },
        ),
        migrations.AddField(
            model_name='center',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='center_district', to='dispatch_sys.district'),
        ),
        migrations.AddField(
            model_name='department',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='dispatch_sys.faculty'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=500)),
                ('nic', models.CharField(max_length=15, unique=True)),
                ('s_no', models.CharField(max_length=15)),
                ('reg_no', models.CharField(max_length=15)),
                ('email', models.EmailField(default='none', max_length=254)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_center', to='dispatch_sys.center')),
                ('degree_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_degree', to='dispatch_sys.degreeprogram')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_district', to='dispatch_sys.district')),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='ReceivedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_received', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dispatch_sys.book')),
                ('center_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dispatch_sys.centerbook')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dispatch_sys.student')),
            ],
            options={
                'db_table': 'received_book',
            },
        ),
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateField(auto_now_add=True)),
                ('grade', models.CharField(blank=True, max_length=5, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='dispatch_sys.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='dispatch_sys.student')),
            ],
            options={
                'db_table': 'student_course',
            },
        ),
        migrations.CreateModel(
            name='StudentCourseRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_year', models.IntegerField()),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_registrations', to='dispatch_sys.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_registrations', to='dispatch_sys.student')),
            ],
            options={
                'db_table': 'student_course_registration',
            },
        ),
        migrations.CreateModel(
            name='StudentQRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='student_qr_codes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qr_code', to='dispatch_sys.student')),
            ],
        ),
        migrations.CreateModel(
            name='DegreeProgramCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_offered', models.IntegerField(default=1)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dispatch_sys.course')),
                ('degree_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dispatch_sys.degreeprogram')),
            ],
            options={
                'db_table': 'degree_program_course',
                'unique_together': {('degree_program', 'course')},
            },
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['nic'], name='student_nic_b49560_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['reg_no'], name='student_reg_no_10aea7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentcourse',
            unique_together={('student', 'course')},
        ),
        migrations.AlterUniqueTogether(
            name='studentcourseregistration',
            unique_together={('student', 'course', 'register_year')},
        ),
    ]
