# Generated by Django 5.2.7 on 2025-10-22 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center_name', models.CharField(max_length=100)),
                ('tel_no', models.CharField(max_length=12)),
            ],
            options={
                'db_table': 'center',
            },
        ),
        migrations.CreateModel(
            name='DegreeProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_program', models.CharField(max_length=100)),
                ('info', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'degree_program',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(max_length=100)),
                ('info', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'district',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=500)),
                ('nic', models.CharField(max_length=15)),
                ('s_no', models.CharField(max_length=15)),
                ('reg_no', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'student',
                'indexes': [models.Index(fields=['nic'], name='student_nic_b49560_idx'), models.Index(fields=['reg_no'], name='student_reg_no_10aea7_idx')],
            },
        ),
    ]
