# Generated by Django 5.2.7 on 2025-10-22 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch_sys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='nic',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
