# Generated by Django 5.2.7 on 2026-01-10 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch_sys', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='degreeprogram',
            name='student',
        ),
        migrations.AddField(
            model_name='student',
            name='degree_program',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='student_degree', to='dispatch_sys.degreeprogram'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='StudentQRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='student_qr_codes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qr_code', to='dispatch_sys.student')),
            ],
        ),
    ]
