# Generated by Django 5.2.7 on 2026-01-11 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch_sys', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentcourse',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='studentcourse',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentcourse',
            name='register_year',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentcourse',
            name='enrollment_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterUniqueTogether(
            name='studentcourse',
            unique_together={('student', 'course', 'register_year')},
        ),
        migrations.DeleteModel(
            name='StudentCourseRegistration',
        ),
    ]
