# Generated by Django 5.2.7 on 2026-01-10 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch_sys', '0002_remove_degreeprogram_student_student_degree_program_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default='none', max_length=254),
        ),
    ]
