# Generated by Django 5.2.7 on 2026-01-13 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch_sys', '0002_alter_studentcourse_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_date', models.DateTimeField(auto_now_add=True)),
                ('expected_pickup_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COLLECTED', 'Collected'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='dispatch_sys.book')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_reservations', to='dispatch_sys.center')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_reservations', to='dispatch_sys.student')),
            ],
            options={
                'db_table': 'book_reservations',
                'ordering': ['-created_at'],
                'unique_together': {('student', 'book', 'status')},
            },
        ),
    ]
