# Generated by Django 5.2.7 on 2026-01-20 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch_sys', '0003_bookreservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receivedbook',
            name='book',
        ),
    ]
