# Generated by Django 5.2.7 on 2026-01-20 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch_sys', '0004_remove_receivedbook_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivedbook',
            name='center_book_course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dispatch_sys.course'),
            preserve_default=False,
        ),
    ]
