# Generated by Django 5.2.7 on 2026-01-20 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch_sys', '0005_receivedbook_center_book_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='center',
            old_name='center_name',
            new_name='c_name',
        ),
    ]
