# Generated by Django 5.2.7 on 2026-01-21 06:35

import dispatch_sys.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch_sys', '0006_rename_center_name_center_c_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degreeprogramcourse',
            name='year_offered',
            field=models.IntegerField(default=dispatch_sys.models.current_year, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2026)]),
        ),
    ]
