# Generated by Django 5.2.7 on 2026-01-21 07:47

import dispatch_sys.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch_sys', '0007_alter_degreeprogramcourse_year_offered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcourse',
            name='register_year',
            field=models.IntegerField(default=dispatch_sys.models.current_year, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2026)]),
        ),
    ]
