# Generated by Django 5.2.7 on 2026-03-02 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch_sys', '0008_alter_studentcourse_register_year'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookreservation',
            unique_together={('student', 'book', 'is_active')},
        ),
        migrations.AddField(
            model_name='bookreservation',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
