# Generated by Django 5.2.7 on 2026-03-05 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch_sys', '0009_alter_bookreservation_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='years',
        ),
        migrations.AddField(
            model_name='course',
            name='months',
            field=models.IntegerField(default=12),
        ),
    ]
