# Generated by Django 5.2.7 on 2026-03-07 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch_sys', '0010_remove_course_years_course_months'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcourse',
            name='is_book_available',
            field=models.BooleanField(default=True),
        ),
    ]
