# Generated by Django 5.2.7 on 2026-03-07 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch_sys', '0011_studentcourse_is_book_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(default='none', max_length=254, unique=True),
        ),
    ]
