# Generated by Django 5.2.7 on 2026-03-12 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch_sys', '0012_alter_student_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='centerbook',
            name='course_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='center_course', to='dispatch_sys.course'),
            preserve_default=False,
        ),
    ]
