# Generated by Django 5.2.7 on 2026-03-12 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch_sys', '0013_centerbook_course_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='centerbook',
            name='course_id',
        ),
    ]
